//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumnosAPI10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursos
    {
        public int id { get; set; }
        public Nullable<int> ano { get; set; }
        public string letra { get; set; }
        public Nullable<int> cicloID { get; set; }
    }
}
